### ISSUE TITLE
Docker compose up not working

### ISSUE THREAD

**Issue by mentalrob** [useplunk/plunk#154]
```
plunk-1  | Starting Prisma migrations...
plunk-1  | prisma:warn Prisma failed to detect the libssl/openssl version to use, and may not work as expected. Defaulting to "openssl-1.1.x".
plunk-1  | Please manually install OpenSSL and try installing Prisma again.
plunk-1  | prisma:warn Prisma failed to detect the libssl/openssl version to use, and may not work as expected. Defaulting to "openssl-1.1.x".
plunk-1  | Please manually install OpenSSL and try installing Prisma again.
plunk-1  | Prisma schema loaded from prisma/schema.prisma
plunk-1  | Datasource "db": PostgreSQL database "postgres", schema "public" at "db:5432"
plunk-1  |
plunk-1  | Error: Could not parse schema engine response: SyntaxError: Unexpected token 'E', "Error load"... is not valid JSON
plunk-1  | npm notice
plunk-1  | npm notice New major version of npm available! 10.8.2 -> 11.1.0
plunk-1  | npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.1.0
plunk-1  | npm notice To update run: npm install -g npm@11.1.0
plunk-1  | npm notice
```

I'm getting this issue while testing with this docker compose

```
version: '3'
services:
  plunk:
    image: "driaug/plunk"
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      REDIS_URL: '${REDIS_URL:-redis://redis:6379}'
      DATABASE_URL: '${DATABASE_URL:-postgresql://postgres:postgres@db:5432/postgres}'
      JWT_SECRET: '${JWT_SECRET}'
      AWS_REGION: '${AWS_REGION}'
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      AWS_SES_CONFIGURATION_SET: '${AWS_SES_CONFIGURATION_SET}'
      NEXT_PUBLIC_API_URI: '${API_URI}'
      API_URI: '${API_URI}'
      APP_URI: '${APP_URI}'
      DISABLE_SIGNUPS: 'False'
    entrypoint: [ "/app/entry.sh" ]
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      retries: 5
      timeout: 10s
  redis:
    image: redis
```
I take this docker compose from documentation
