### ISSUE TITLE
Issue with https request to the api

### ISSUE THREAD

**Issue by Iulian-Dragomirescu** [useplunk/plunk#43]
Hello, I tried this open source project today, but I encountered a problem with the request made by the UI to the Backend over `HTTPS`

my env file for api is: 
```
API_URI=https://plunk.exemple/api
APP_URI=https://plunk.exemple.ro
```

but in the request made by the UI to the Backend it is like this:
```https://plunk.exemple.ro/plunk.exemple.ro/api/users/@me``` is `404 Not Found`

**Comment by driaug** [comment]
What is your .env file for the dashboard?

**Comment by Iulian-Dragomirescu** [comment]
Is not locally, i use coolify on a VPS
The env is managed by coolify with 

```
API_URI=https://plunk.exemple/api
APP_URI=https://plunk.exemple.ro

AWS... etc
```
This is the docker-compose file
```
version: '3'
services:
  plunk:
    image: driaug/plunk
    ports:
      - '3001:5000'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      REDIS_URL: 'redis://redis:6379'
      DATABASE_URL: 'postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres'
      JWT_SECRET: '${JWT_SECRET}'
      AWS_REGION: '${AWS_REGION}'
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      AWS_SES_CONFIGURATION_SET: '${AWS_SES_CONFIGURATION_SET}'
      NEXT_PUBLIC_API_URI: '${API_URI}'
      API_URI: '${API_URI}'
      APP_URI: '${APP_URI}'
      DISABLE_SIGNUPS: '${DISABLE_SIGNUPS}'
    entrypoint:
      - /app/entry.sh
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U postgres -d postgres'
      interval: 10s
      retries: 5
      timeout: 10s
  redis:
    image: redis

```

**Comment by driaug** [comment]
I believe it might be because your API_URI is not a valid URL.
Everything else looks fine.

**Comment by angelhodar** [comment]
@driaug I am facing the same issue trying to deploy it self hosted with dokploy via docker image. I have tried multiple combinations and the problem is that the request made to the backend is as described by @Iulian-Dragomirescu. Also there is a variable called NEXT_PUBLIC_API_URI that is used but not described in the docs. I have seen the variables usage in the code and what makes sense for me is this, or at least it doesnt crash the server:

NEXT_PUBLIC_API_URI=/api
API_URI=https://emails.angelhodar.com/api
APP_URI=emails.angelhodar.com

With this config, if I try to create an account from the /auth/signup page it makes the request to:

https://emails.angelhodar.com/auth/emails.angelhodar.com/api/auth/signup

Are we missing something?

**Comment by jaaneh** [comment]
![image](https://github.com/user-attachments/assets/1ac6ef9a-a56c-4dd6-8770-bd40e1882a51)
Also unfortunately seeing the same issue with signing up. I'm on Railway. The request is sent to `https://<subdomain>.up.railway.app/api/auth/signup` and `https://<subdomain>.up.railway.app/api/users/@me` but receives 404

env is set to
```
API_URI="https://<subdomain>.up.railway.app/api"
APP_URI="https://<subdomain>.up.railway.app"
```

**Comment by Iulian-Dragomirescu** [comment]
now, `https://plunk.exemple.ro/plunk.exemple.ro/api/users/@me` no longer appears, and it is a correct format (`
https://plunk.exemple.ro/api/auth/signup`), but it is 404.. same as @jaaneh

**Comment by driaug** [comment]
I myself always test using the Docker Compose setup provided in the docs.

This maps everything appropriately since `API_URI` and `NEXT_PUBLIC_API_URI` should be the same.
My setup looks like this and runs flawlessly.

```.env
API_URI=https://plunk.example.com/api
APP_URI=https://plunk.example.com
```

```yml
version: '3'
services:
  plunk:
    image: "driaug/plunk"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      REDIS_URL: '${REDIS_URL:-redis://redis:6379}'
      DATABASE_URL: '${DATABASE_URL:-postgresql://postgres:postgres@db:5432/postgres}'
      JWT_SECRET: '${JWT_SECRET}'
      AWS_REGION: '${AWS_REGION}'
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      AWS_SES_CONFIGURATION_SET: '${AWS_SES_CONFIGURATION_SET}'
      NEXT_PUBLIC_API_URI: '${API_URI}'
      API_URI: '${API_URI}'
      APP_URI: '${APP_URI}'
      DISABLE_SIGNUPS: 'False'
    entrypoint: [ "/app/entry.sh" ]
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      retries: 5
      timeout: 10s
  redis:
    image: redis
```
