### ISSUE TITLE
unknown fetch failed from backend

### ISSUE THREAD

**Issue by lionep** [useplunk/plunk#44]
Hey ! Nice project here, thank you very much for opensourcing it !

I have a crash about 1 minute after backend is starting.

In docker-compose logs : 

```
backend-1  | ℹ  info      Running scheduled tasks
backend-1  | ℹ  info      Updating verified identities
backend-1  | node:internal/deps/undici/undici:13178
backend-1  |       Error.captureStackTrace(err);
backend-1  |             ^
backend-1  |
backend-1  | TypeError: fetch failed
backend-1  |     at node:internal/deps/undici/undici:13178:13
backend-1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
backend-1  |     at runNextTicks (node:internal/process/task_queues:64:3)
backend-1  |     at process.processImmediate (node:internal/timers:454:9) {
backend-1  |   [cause]: ConnectTimeoutError: Connect Timeout Error
backend-1  |       at onConnectTimeout (node:internal/deps/undici/undici:2331:28)
backend-1  |       at node:internal/deps/undici/undici:2283:50
backend-1  |       at Immediate._onImmediate (node:internal/deps/undici/undici:2315:13)
backend-1  |       at process.processImmediate (node:internal/timers:483:21) {
backend-1  |     code: 'UND_ERR_CONNECT_TIMEOUT'
backend-1  |   }
backend-1  | }
```

Here is the docker-compose.yml (plunk is hosted behind traefik)

```
version: '3'

services:
  backend:
    image: driaug/plunk:latest
    labels:
      - traefik.http.routers.${SERVICE_NAME}httpRouter.rule=Host(`${SERVICE_HOST}`)
      - traefik.http.routers.${SERVICE_NAME}httpRouter.entrypoints=http
      - traefik.http.routers.${SERVICE_NAME}httpRouter.middlewares=${SERVICE_NAME}redirect
      - traefik.http.middlewares.${SERVICE_NAME}redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.${SERVICE_NAME}redirect.redirectscheme.port=443
      - traefik.http.routers.${SERVICE_NAME}httpsRouter.rule=Host(`${SERVICE_HOST}`)
      - traefik.http.routers.${SERVICE_NAME}httpsRouter.entrypoints=https
      - traefik.http.routers.${SERVICE_NAME}httpsRouter.tls=true
      - traefik.http.routers.${SERVICE_NAME}httpsRouter.tls.certresolver=letsEncryptResolver
      - traefik.enable=true
    environment:
      - AWS_REGION=XX-XXXXX-XX
      - NEXT_PUBLIC_AWS_REGION=XX-XXXXX-XX
      - AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXX
      - AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - AWS_SES_CONFIGURATION_SET=plunk-configuration-set
      - JWT_SECRET=SUPER_SECRET_KEY
      - APP_URI=plunk.mydomain.com
      - API_URI=https://plunk.mydomain.com/api
      - NEXT_PUBLIC_API_URI=plunk.mydomain.com
      - DISABLE_SIGNUPS=False
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:SUPER_SECRET_PASSWORD@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    entrypoint: [ "/app/entry.sh" ]
    networks:
      - plunk
      - traefik

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: SUPER_SECRET_PASSWORD
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      retries: 5
      timeout: 10s
    networks:
      - plunk

  redis:
    image: redis
    networks:
      - plunk

networks:
  plunk:
  traefik:
    external:
      name: traefik_network
```

Thanks, let me know if I can provide more info with this.
